### ISSUE TITLE
mieze: check adiabatic transition

### ISSUE THREAD

**Issue by HGabold** [dprelipcean/mieze-simulation#56]

**Comment by dprelipcean** [comment]
@HGabold I made the adiabatic transition script to run and have some initial plots: [bx vs by](https://github.com/dprelipcean/mieze-simulation/blob/master/docs/experiments/by_bx.png) and [adiabatic transition](https://github.com/dprelipcean/mieze-simulation/blob/master/docs/experiments/mieze_condition.png). Could you inspect whether this is how they are supposed to look like? They are made from a Helmholtz Coil, SpinFlipper and RealCoil, and please ignore the values at 0 for the moment.
